/*
	"ESB" is designed to create external native components for the 1C(tm) program.
	Copyright © 2023 IntUnsigned	(v8classes@gmail.com)
	"ESB" is free software under LGPLv2.1 license with essential restriction about binary part (view esb-license.txt)
	"ESB" IS DISTRIBUTED "AS-IS" WITHOUT ANY, EVEN THE IMPLIED, WARRANTY. IN NO EVENT SHALL THE AUTHORS OR THE COPYRIGHT OWNER BE LIABLE FOR ANY CLAIM, 
	DAMAGES OR OTHER LIABILITY ARISING OUT OF THE USE OF THIS SOFTWARE.
	THE AUTHOR DOES NOT GIVE ANY GUARANTEES AND DOES NOT BEAR ANY RESPONSIBILITY REGARDING THE USE OF 1C(tm) COMPONENTS PRODUCED USING THE ESB LIBRARY IN THE 1C(tm) ENVIRONMENT.
*/
#pragma once
#ifndef ESB_ESDISP_FILE_H_
#define ESB_ESDISP_FILE_H_

/*
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! AutoGenerated Dispinfo File 	!!
!! DO NOT EDIT					!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
// platform ver v8.3.23.1688
#include "esdisp.h"


namespace esb {
	//
#define ESBLIB_TYPE(CLASS_EN_, ...)		class CLASS_EN_;
#define ESBLIB_ENUM(CLASS_EN_, ...)		ESBLIB_TYPE(CLASS_EN_)
#include "es1_file.def.h"

	namespace _internal 
	{
		namespace _dispinfo
		{
			namespace _v8323
			{

template<>
struct EnumIdsFor<PositionInStream> {
enum _ids_enum : dispix_t {Begin, Current, End};
static constexpr dispix_t _ids_enum_count = 3;
};
template<>
struct EnumIdsFor<ByteOrder> {
enum _ids_enum : dispix_t {LittleEndian, BigEndian};
static constexpr dispix_t _ids_enum_count = 2;
};
template<>
struct EnumIdsFor<FileOpenMode> {
enum _ids_enum : dispix_t {Create, CreateNew, Open, OpenOrCreate, Truncate, Append};
static constexpr dispix_t _ids_enum_count = 6;
};
template<>
struct EnumIdsFor<FileAccess> {
enum _ids_enum : dispix_t {Read, Write, ReadAndWrite};
static constexpr dispix_t _ids_enum_count = 3;
};
template<>
struct MethIdsFor<Stream> {
enum _ids_enum : dispix_t {Close, Size, GetReadOnlyStream, CurrentPosition, CopyTo, Flush, Seek, SetSize, Read, Write, BeginGetSize, SizeAsync, BeginCopyTo, CopyToAsync, BeginSeek, SeekAsync, BeginSetSize, SetSizeAsync, BeginRead, ReadAsync, BeginWrite, WriteAsync, BeginFlush, FlushAsync, BeginClose, CloseAsync};
static constexpr dispix_t _ids_enum_count = 26;
};
template<>
struct PropIdsFor<Stream> {
enum _ids_enum : dispix_t {CanRead, CanWrite, CanSeek};
static constexpr dispix_t _ids_enum_count = 3;
};
template<>
struct MethIdsFor<BinaryData> {
enum _ids_enum : dispix_t {Write, Size, OpenStreamForRead, BeginWrite, WriteAsync};
static constexpr dispix_t _ids_enum_count = 5;
};
template<>
struct PropIdsFor<BinaryData> {
// No Disp Properties.
};
template<>
struct MethIdsFor<BinaryDataBuffer> {
enum _ids_enum : dispix_t {SetReadOnly, GetSlice, Get, Set, Read, ReadInt16, ReadInt32, ReadInt64, WriteInt16, WriteInt32, WriteInt64, Copy, Write, Reverse, Concat, Split, WriteBitwiseAnd, WriteBitwiseOr, WriteBitwiseXor, WriteBitwiseAndNot, Invert};
static constexpr dispix_t _ids_enum_count = 21;
};
template<>
struct PropIdsFor<BinaryDataBuffer> {
enum _ids_enum : dispix_t {Size, ReadOnly, ByteOrder};
static constexpr dispix_t _ids_enum_count = 3;
};
template<>
struct MethIdsFor<FileStream> {
enum _ids_enum : dispix_t {Close, Size, GetReadOnlyStream, CurrentPosition, CopyTo, Flush, Seek, SetSize, Read, Write, BeginGetSize, SizeAsync, BeginCopyTo, CopyToAsync, BeginSeek, SeekAsync, BeginSetSize, SetSizeAsync, BeginRead, ReadAsync, BeginWrite, WriteAsync, BeginFlush, FlushAsync, BeginClose, CloseAsync};
static constexpr dispix_t _ids_enum_count = 26;
};
template<>
struct PropIdsFor<FileStream> {
enum _ids_enum : dispix_t {CanRead, CanWrite, CanSeek, FileName};
static constexpr dispix_t _ids_enum_count = 4;
};
template<>
struct MethIdsFor<MemoryStream> {
enum _ids_enum : dispix_t {Close, Size, GetReadOnlyStream, CurrentPosition, CopyTo, Flush, Seek, SetSize, Read, Write, BeginGetSize, SizeAsync, BeginCopyTo, CopyToAsync, BeginSeek, SeekAsync, BeginSetSize, SetSizeAsync, BeginRead, ReadAsync, BeginWrite, WriteAsync, BeginFlush, FlushAsync, BeginClose, CloseAsync, CloseAndGetBinaryData};
static constexpr dispix_t _ids_enum_count = 27;
};
template<>
struct PropIdsFor<MemoryStream> {
enum _ids_enum : dispix_t {CanRead, CanWrite, CanSeek};
static constexpr dispix_t _ids_enum_count = 3;
};


			} //_v8323
		} //_dispinfo
	}// _internal
}// esb
#endif	//ESB_ESDISP_FILE_H_
