/*
	"ESB" is designed to create external native components for the 1C(tm) program.
	Copyright © 2023 IntUnsigned	(v8classes@gmail.com)
	"ESB" is free software under LGPLv2.1 license with essential restriction about binary part (view esb-license.txt)
	"ESB" IS DISTRIBUTED "AS-IS" WITHOUT ANY, EVEN THE IMPLIED, WARRANTY. IN NO EVENT SHALL THE AUTHORS OR THE COPYRIGHT OWNER BE LIABLE FOR ANY CLAIM, 
	DAMAGES OR OTHER LIABILITY ARISING OUT OF THE USE OF THIS SOFTWARE.
	THE AUTHOR DOES NOT GIVE ANY GUARANTEES AND DOES NOT BEAR ANY RESPONSIBILITY REGARDING THE USE OF 1C(tm) COMPONENTS PRODUCED USING THE ESB LIBRARY IN THE 1C(tm) ENVIRONMENT.
*/
#pragma once
#ifndef ESB_ESDISP_ALL_H_
#define ESB_ESDISP_ALL_H_

/*
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! AutoGenerated Dispinfo File 	!!
!! DO NOT EDIT					!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
// platform ver v8.3.9.1818
#include "esdisp.h"


#include "esdisp_base.h"
#include "esdisp_main.h"
#include "esdisp_data.h"
#include "esdisp_file.h"
#include "esdisp_api.h"

#endif	//ESB_ESDISP_ALL_H_
